# Generated by Django 4.2.1 on 2023-07-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=300)),
                ('Idade', models.IntegerField()),
            ],
        ),
    ]
